import turtle
turtle.Screen().bgcolor("Orange")
board = turtle.Turtle()
turtle.forward(60)
turtle.right(60)
turtle.forward(60)
turtle.right(60)
turtle.forward(60)
turtle.right(60)
turtle.forward(60)
turtle.right(60)
turtle.forward(60)
turtle.right(60)
turtle.forward(60)
turtle.right(60)
turtle.done()